### ISSUE TITLE
Should support common keyboard commands

### ISSUE THREAD

**Issue by adly-mmob** [slebetman/piq#3]
More keyboard commands should be supported:

All Windows (except preferences):
- ~~CtrlOrCmd+F should toggle full screen~~
- ~~ESC should exit full screen~~

Image Browser:
- ~~Backspace should go to parent folder (like browser back button)~~
- ~~PageUp and PageDown should scroll~~

Image Viewer:
- ~~CtrlOrCmd+0 = full size (or fit to monitor)~~
- ~~CtrlOrCmd+1 = 1/2 size (or fit to monitor)~~
- ~~CtrlOrCmd+2 = 1/3 size~~
- ~~CtrlOrCmd+3 = 1/4 size~~

**Comment by slebetman** [comment]
Done
